app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activepieces-app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - AP_CONTAINER_TYPE=APP
    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - activepieces
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    env_file:
      - .env
    environment:
      - AP_CONTAINER_TYPE=WORKER
    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - activepieces
